name: TDR Deploy Notifications Lambda
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - intg
          - staging
          - prod
          - mgmt
        default: 'intg'
      to-deploy:
        description: 'Version to deploy'
        required: true

permissions:
  id-token: write
  contents: write
jobs:
  deploy:
    uses: nationalarchives/tdr-github-actions/.github/workflows/lambda_deploy.yml@TDR-3373_do_not_run_e2e_test_for_mgmt_env
    with:
      lambda-name: notifications
      deployment-package: notifications.jar
      environment: ${{ github.event.inputs.environment }}
      to-deploy: ${{ github.event.inputs.to-deploy }}
    secrets:
      ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
