name: PR update

on:
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically update PR
        uses: adRise/update-pr-branch@v0.9.1
        with:
          token: ${{ secrets.WORKFLOW_PAT }}
          base: 'master'
          required_approval_count: 0
          require_passed_checks: false